<a href="https://colab.research.google.com/github/imgautam1/xyz2/blob/main/Final_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Print Hello World

In [ ]:
print("Hello")

Hello


 1.1 Demonstrate functions and all categories of functions in C/C++/java/python.

In [ ]:
# 1. No args, no return
def greet():
    print("Hello!")

# 2. Args, no return
def print_sum(a, b):
    print("Sum:", a + b)

# 3. No args, return value
def get_five():
    return 5


# 4. Args and return value
def multiply(x, y):
    return x * y

# Main
greet()
print_sum(2, 3)
print("Got:", get_five())
print("Product:", multiply(4, 6))


Hello!
Sum: 5
Got: 5
Product: 24


1.2 Demonstrate arrays (Insertion, Deletion, arithmetic operations).

In [ ]:
# Import necessary library
import numpy as np

print("=== ARRAY INSERTION ===")
arr = [10, 20, 30, 40]
print("Original Array:", arr)

# Insert 25 at index 2
arr.insert(2, 25)
print("After Insertion at index 2:", arr)

print("\n=== ARRAY DELETION ===")
# Delete element at index 3
del arr[3]
print("After Deletion at index 3:", arr)

print("\n=== ARITHMETIC OPERATIONS ===")
# Convert to NumPy arrays for arithmetic
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Perform operations
print("Array A:", a)
print("Array B:", b)
print("Addition (A + B):", a + b)
print("Subtraction (A - B):", a - b)
print("Multiplication (A * B):", a * b)
print("Division (A / B):", a / b)


=== ARRAY INSERTION ===
Original Array: [10, 20, 30, 40]
After Insertion at index 2: [10, 20, 25, 30, 40]

=== ARRAY DELETION ===
After Deletion at index 3: [10, 20, 25, 40]

=== ARITHMETIC OPERATIONS ===
Array A: [1 2 3]
Array B: [4 5 6]
Addition (A + B): [5 7 9]
Subtraction (A - B): [-3 -3 -3]
Multiplication (A * B): [ 4 10 18]
Division (A / B): [0.25 0.4  0.5 ]


1.3 Perform Addition, Multiplication for Vectors and Matrices.

In [ ]:
# Import NumPy
import numpy as np

# --- Vector Operations ---
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Vector Addition
vector_add = v1 + v2

# Vector Multiplication (Dot Product)
vector_dot = np.dot(v1, v2)

print("Vector 1:", v1)
print("Vector 2:", v2)
print("Vector Addition:", vector_add)
print("Vector Dot Product:", vector_dot)

print("\n" + "-"*40 + "\n")

# --- Matrix Operations ---
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

# Matrix Addition
matrix_add = m1 + m2

# Matrix Multiplication
matrix_mul = np.dot(m1, m2)

print("Matrix 1:\n", m1)
print("Matrix 2:\n", m2)
print("Matrix Addition:\n", matrix_add)
print("Matrix Multiplication:\n", matrix_mul)


Vector 1: [1 2 3]
Vector 2: [4 5 6]
Vector Addition: [5 7 9]
Vector Dot Product: 32

----------------------------------------

Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[5 6]
 [7 8]]
Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


1.4 Practical based on Strings (Length finding, change specific character palindrome, concatenation)

In [ ]:
def string_operations():
    s = input("Enter a string: ")
    print(f"Length: {len(s)}")

    # Change 'e' to 'i'
    modified = s.replace('e', 'i')
    print(f"Modified: {modified}")

    # Check palindrome
    print(f"Palindrome: {'Yes' if s.lower() == s[::-1].lower() else 'No'}")

    # Concatenation
    concat = s + " " + input("Enter another string: ")
    print(f"Concatenated: {concat}")

string_operations()


Enter a string: veshwa
Length: 6
Modified: vishwa
Palindrome: No
Enter another string: jeyaa
Concatenated: veshwa jeyaa


1.5 Create a menu driven program to show various operators supported by python.

In [ ]:
# Python Menu Driven Program to Show Various Operators

def arithmetic_operators():
    print("\nArithmetic Operators:")
    a, b = 10, 5
    print(f"a = {a}, b = {b}")
    print(f"a + b = {a + b}")
    print(f"a - b = {a - b}")
    print(f"a * b = {a * b}")
    print(f"a / b = {a / b}")
    print(f"a % b = {a % b}")
    print(f"a ** b = {a ** b}")
    print(f"a // b = {a // b}")

def comparison_operators():
    print("\nComparison Operators:")
    a, b = 10, 5
    print(f"a = {a}, b = {b}")
    print(f"a == b: {a == b}")
    print(f"a != b: {a != b}")
    print(f"a > b: {a > b}")
    print(f"a < b: {a < b}")
    print(f"a >= b: {a >= b}")
    print(f"a <= b: {a <= b}")

def logical_operators():
    print("\nLogical Operators:")
    x, y = True, False
    print(f"x = {x}, y = {y}")
    print(f"x and y = {x and y}")
    print(f"x or y = {x or y}")
    print(f"not x = {not x}")

def assignment_operators():
    print("\nAssignment Operators:")
    a = 10
    print(f"a = {a}")
    a += 5
    print(f"a += 5: {a}")
    a -= 3
    print(f"a -= 3: {a}")
    a *= 2
    print(f"a *= 2: {a}")
    a /= 4
    print(f"a /= 4: {a}")
    a %= 3
    print(f"a %= 3: {a}")

def bitwise_operators():
    print("\nBitwise Operators:")
    a, b = 5, 3  # In binary: a = 0101, b = 0011
    print(f"a = {a}, b = {b}")
    print(f"a & b = {a & b}")  # AND
    print(f"a | b = {a | b}")  # OR
    print(f"a ^ b = {a ^ b}")  # XOR
    print(f"~a = {~a}")  # NOT
    print(f"a << 1 = {a << 1}")  # Left shift
    print(f"a >> 1 = {a >> 1}")  # Right shift

def membership_operators():
    print("\nMembership Operators:")
    lst = [1, 2, 3, 4, 5]
    print(f"lst = {lst}")
    print(f"3 in lst: {3 in lst}")
    print(f"6 not in lst: {6 not in lst}")

def identity_operators():
    print("\nIdentity Operators:")
    x = [1, 2, 3]
    y = x
    z = [1, 2, 3]
    print(f"x = {x}, y = {y}, z = {z}")
    print(f"x is y: {x is y}")  # True, as both refer to the same object
    print(f"x is z: {x is z}")  # False, as they refer to different objects
    print(f"x == z: {x == z}")  # True, as values are the same

def main():
    while True:
        print("\nChoose an operator category to learn about:")
        print("1. Arithmetic Operators")
        print("2. Comparison Operators")
        print("3. Logical Operators")
        print("4. Assignment Operators")
        print("5. Bitwise Operators")
        print("6. Membership Operators")
        print("7. Identity Operators")
        print("8. Exit")

        choice = input("Enter your choice (1-8): ")

        if choice == '1':
            arithmetic_operators()
        elif choice == '2':
            comparison_operators()
        elif choice == '3':
            logical_operators()
        elif choice == '4':
            assignment_operators()
        elif choice == '5':
            bitwise_operators()
        elif choice == '6':
            membership_operators()
        elif choice == '7':
            identity_operators()
        elif choice == '8':
            print("Exiting program...")
            break
        else:
            print("Invalid choice, please try again!")

# Run the program
main()



Choose an operator category to learn about:
1. Arithmetic Operators
2. Comparison Operators
3. Logical Operators
4. Assignment Operators
5. Bitwise Operators
6. Membership Operators
7. Identity Operators
8. Exit

Membership Operators:
lst = [1, 2, 3, 4, 5]
3 in lst: True
6 not in lst: True

Choose an operator category to learn about:
1. Arithmetic Operators
2. Comparison Operators
3. Logical Operators
4. Assignment Operators
5. Bitwise Operators
6. Membership Operators
7. Identity Operators
8. Exit


1.6 Write a python program to find out if a given
number is even or odd using a user defined
function.

In [ ]:
def check_even_odd(number):
  # The modulo operator (%) gives the remainder of a division.
  # If a number divided by 2 has a remainder of 0, it's even.
  if number % 2 == 0:
    return "Even"
  else:
    return "Odd"

# Ask the user to enter a number
user_number = int(input("Please enter a whole number: "))

# Call the function with the user's number
result = check_even_odd(user_number)

# Print the result
print(f"The number {user_number} is {result}.")

Please enter a whole number: 33
The number 33 is Odd.


1.7 1) Addition of first 15 numbers using loop. 2)
Addition of any 15 numbers using a loop.

1.8 Write a python program to check if the entered year is leap year or not.

In [ ]:
def is_leap(year):
  # A year is a leap year if it is divisible by 4,
  # except for years divisible by 100 but not by 400.
  if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    return True
  else:
    return False

# Get the year from the user
try:
  year_to_check = int(input("Enter a year: "))

  # Check if it's a leap year using the function
  if is_leap(year_to_check):
    print(f"{year_to_check} is a leap year.")
  else:
    print(f"{year_to_check} is not a leap year.")

except ValueError:
  print("Invalid input. Please enter a valid year (a whole number).")

Enter a year: 2024
2024 is a leap year.


1.9 Write a Python program which accepts the user's first and last name and print them in reverse order with a space between them.

In [ ]:
# Get the first name from the user
first_name = input("Enter your first name: ")

# Get the last name from the user
last_name = input("Enter your last name: ")

# Print the last name, a space, and then the first name
print(last_name + " " + first_name)

# Alternatively, using an f-string for clearer formatting:
# print(f"{last_name} {first_name}")

Enter your first name: abccc
Enter your last name: xyzzz
xyzzz abccc


1.10 Write a Python program to print the calendar of a given month and year.

In [ ]:
# Import the calendar module
import calendar

# Get the year from the user
try:
    year = int(input("Enter the year: "))

    # Get the month from the user
    month = int(input("Enter the month (1-12): "))

    # Validate the month input
    if 1 <= month <= 12:
        # Print the calendar for the given month and year
        print("\nHere is the calendar:")
        print(calendar.month(year, month))
    else:
        print("Invalid month entered. Please enter a number between 1 and 12.")

except ValueError:
    print("Invalid input. Please enter valid integer numbers for year and month.")

Enter the year: 2
Enter the month (1-12): 1

Here is the calendar:
     January 2
Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6
 7  8  9 10 11 12 13
14 15 16 17 18 19 20
21 22 23 24 25 26 27
28 29 30 31



1.11 Write a Python program to check whether a specified value is contained in a group of values. Test Data: c. -> [1, 5, 8, 3]: True -1 -> [1, 5, 8, 3]: False

In [ ]:
# Function to check if a value is in a group of values
def is_in_group(value, group):
  # The 'in' operator checks for membership in a list (or other iterable)
  if value in group:
    return True
  else:
    return False

# Test Data 1: Check if 8 is in the list [1, 5, 8, 3]
test_group_1 = [1, 5, 8, 3]
test_value_1 = 8
result_1 = is_in_group(test_value_1, test_group_1)
print(f"Is {test_value_1} in {test_group_1}? {result_1}") # Expected Output: True

# Test Data 2: Check if -1 is in the list [1, 5, 8, 3]
test_group_2 = [1, 5, 8, 3]
test_value_2 = -1
result_2 = is_in_group(test_value_2, test_group_2)
print(f"Is {test_value_2} in {test_group_2}? {result_2}") # Expected Output: False

# You can also get input from the user to test
# user_value = int(input("Enter a value to check: "))
# user_group = [10, 20, 30, 40] # Example list
# print(f"Is {user_value} in {user_group}? {is_in_group(user_value, user_group)}")

Is 8 in [1, 5, 8, 3]? True
Is -1 in [1, 5, 8, 3]? False


1.12 Write a Python program to get OS name, platform and release information.

In [ ]:
# Import the platform module
import platform

# Get the OS name
os_name = platform.system()

# Get the platform information
platform_info = platform.platform()

# Get the release information
release_info = platform.release()

# Print the information
print(f"Operating System Name: {os_name}")
print(f"Platform Information: {platform_info}")
print(f"Release Information: {release_info}")

Operating System Name: Linux
Platform Information: Linux-6.1.123+-x86_64-with-glibc2.35
Release Information: 6.1.123+


2.1 Write a function to find out x^y. Function should find out the square of x in case of default argument passing.

In [ ]:
# Ask the user to enter the value of x
x = float(input("Enter value of x: "))

# Ask the user to enter the value of y (optional)
y_input = input("Enter value of y (press Enter to square x): ")

# Check if y was entered
if y_input.strip() == "":
    y = 2  # default to square
else:
    y = float(y_input)

# Calculate x^y
result = x ** y

# Show result
print(f"{x} ^ {y} = {result}")


Enter value of x: 5
Enter value of y (press Enter to square x): 5
5.0 ^ 5.0 = 3125.0


2.2 Write a function to find out the factorial of a given number. I) without recursion II) with recursion

In [ ]:
def factorial_iterative(n):
    fact = 1
    for i in range(1, n + 1):
        fact *= i
    return fact

def factorial_recursive(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial_recursive(n - 1)

# Get input from user
num = int(input("Enter a non-negative number: "))

# Check for negative input
if num < 0:
    print("Factorial is not defined for negative numbers.")
else:
    print(f"\nFactorial of {num} (Iterative) = {factorial_iterative(num)}")
    print(f"Factorial of {num} (Recursive) = {factorial_recursive(num)}")


Enter a non-negative number: 2

Factorial of 2 (Iterative) = 2
Factorial of 2 (Recursive) = 2


2.3 Write a program to find out Fibonacci series using recursion and function as an object.

In [ ]:
def fibonacci(n):
    if n <= 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n - 1) + fibonacci(n - 2)

# Assign function to a variable (function as an object)
fib = fibonacci

# Get number of terms from user
num_terms = int(input("Enter number of terms in Fibonacci series: "))

# Print the Fibonacci series
print("\nFibonacci Series:")
for i in range(num_terms):
    print(fib(i), end=" ")

Enter number of terms in Fibonacci series: 10

Fibonacci Series:
0 1 1 2 3 5 8 13 21 34 

3.1 Write a Python program to check whether a specified value is contained in a group of values using lambda function. Test Data: 3 -> [1, 5, 8, 3] : True -1 -> [1, 5, 8, 3] : False

In [ ]:
# Define a lambda function to check if a value is in a list
# The lambda function takes two arguments: the value to check and the list
check_in_group = lambda value, group: value in group

# Test Data 1: Check if 3 is in the list [1, 5, 8, 3]
test_group_1 = [1, 5, 8, 3]
test_value_1 = 3
result_1 = check_in_group(test_value_1, test_group_1)
print(f"Is {test_value_1} in {test_group_1}? {result_1}") # Expected Output: True

# Test Data 2: Check if -1 is in the list [1, 5, 8, 3]
test_group_2 = [1, 5, 8, 3]
test_value_2 = -1
result_2 = check_in_group(test_value_2, test_group_2)
print(f"Is {test_value_2} in {test_group_2}? {result_2}") # Expected Output: False

Is 3 in [1, 5, 8, 3]? True
Is -1 in [1, 5, 8, 3]? False


3.2 Write a Python program to find whether a given
string ends with a given character using Lambda.

In [ ]:
# Define a lambda function to check if a string ends with a character
# The lambda function takes the string and the character as arguments
ends_with_char = lambda string, char: string.endswith(char)

# Get input from the user for the string and the character
user_string = input("Enter a string: ")
user_char = input("Enter the character to check if the string ends with: ")

# Check if the string ends with the character using the lambda function
if ends_with_char(user_string, user_char):
  print(f"The string '{user_string}' ends with the character '{user_char}'.")
else:
  print(f"The string '{user_string}' does not end with the character '{user_char}'.")

# You can also test with specific examples
# print(ends_with_char("hello", "o")) # Output: True
# print(ends_with_char("world", "d")) # Output: True
# print(ends_with_char("python", "a")) # Output: False

Enter a string: hello
Enter the character to check if the string ends with: python
The string 'hello' does not end with the character 'python'.


3.3 Prime or not prime. Input: L= [3,4,6,9,11] Output: L= [P, NP, NP, NP, P] using map function.

In [ ]:
def is_prime(num):
  """Checks if a number is prime."""
  if num <= 1:
    return False
  for i in range(2, int(num**0.5) + 1):
    if num % i == 0:
      return False
  return True

# Input list
L = [3, 4, 6, 9, 11]

# Use map to apply the is_prime function to each element
# and then map the boolean result to 'P' or 'NP'
result = list(map(lambda x: 'P' if is_prime(x) else 'NP', L))

print(f"Input: L = {L}")
print(f"Output: L = {result}")

Input: L = [3, 4, 6, 9, 11]
Output: L = ['P', 'NP', 'NP', 'NP', 'P']


3.4 Write a python program to find out even numbers from a list using filter ().

In [ ]:
# Sample list
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Define a function to check if a number is even
def is_even(num):
  return num % 2 == 0

# Use filter() to get even numbers
# filter() returns an iterator, so we convert it to a list
even_numbers = list(filter(is_even, numbers))

print(f"Original list: {numbers}")
print(f"Even numbers: {even_numbers}")

# You can also use a lambda function with filter()
# even_numbers_lambda = list(filter(lambda x: x % 2 == 0, numbers))
# print(f"Even numbers (using lambda): {even_numbers_lambda}")

Original list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Even numbers: [2, 4, 6, 8, 10]


4.1 An interactive program where one module asks numbers from the user and the second module performs at least three arithmetic operations on them.

In [ ]:
%%writefile input_module.py
# This module gets numbers from the user

def get_numbers():
    """Prompts the user to enter two numbers and returns them."""
    try:
        num1 = float(input("Enter the first number: "))
        num2 = float(input("Enter the second number: "))
        return num1, num2
    except ValueError:
        print("Invalid input. Please enter valid numbers.")
        return None, None # Return None for invalid input

Overwriting input_module.py


In [ ]:
%%writefile operation_module.py
# This module performs arithmetic operations

def add(x, y):
    """Returns the sum of two numbers."""
    return x + y

def subtract(x, y):
    """Returns the difference between two numbers."""
    return x - y

def multiply(x, y):
    """Returns the product of two numbers."""
    return x * y

def div(x, y): # Correct function name is 'div' and uses parameters x and y
    """Returns the result of dividing the first number by the second."""
    if y != 0:  # Use y instead of b
        return x / y # Use x and y instead of a and b
    else:
        return "Error: Division by zero"

Overwriting operation_module.py


In [ ]:
# This is the main part of the program

import input_module
import operation_module

# Get numbers from the user using the input_module
num1, num2 = input_module.get_numbers()

# Check if input was valid before performing operations
if num1 is not None and num2 is not None:
    # Perform arithmetic operations using the operation_module
    print("\nResults:")
    print(f"Addition: {operation_module.add(num1, num2)}")
    print(f"Subtraction: {operation_module.subtract(num1, num2)}")
    print(f"Multiplication: {operation_module.multiply(num1, num2)}")
    print(f"Division: {operation_module.div(num1, num2)}") # Corrected to use 'div'
else:
    print("\nCould not perform operations due to invalid input.")

Enter first number: 1
Enter second number: 2

Results:
Addition: 3.0
Subtraction: -1.0
Multiplication: 2.0


NameError: name 'b' is not defined